package:
  name: pyhessio
  version: 0.2

source:
  git_url: https://github.com/cta-observatory/pyhessio
  git_branch: master

build:
  number: 1
  binary_relocation: True
  detect_binary_files_with_prefix: True


requirements:
  build:
    - cmake

requirements:
  run:
    - python >=3
    - numpy
